### ISSUE TITLE
[question]: Docker container

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-node#81]
Hi Team!
Does anyone had a chance to run medooze inside the docker container?
What could be possible issues/drawbacks?
Thanks a lot.

**Comment by murillo128** [comment]
I have no personal experience with docker, so it would be worthy know if anyone has tried it and what is their feedback.

Regarding the issues, from what I have read, setting up NAT for a whole block of udp ports may be difficult. And performance may be lowered as well (depending on your workload that may be fine).

**Comment by maxhawkins** [comment]
It works fine if you run it with host networking. I'm running medooze on Kubernetes.

**Comment by murillo128** [comment]
would it be possible to get a simple howto on how to deploy a server using the media server with Kubernetes/Docker?

**Comment by maxhawkins** [comment]
Sure. I use the standard nodejs dockerfile:

```
FROM node:11

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]
```

And this kubernetes config:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: medooze
spec:
  selector:
    matchLabels:
      name: medooze
  template:
    metadata:
      labels:
        name: medooze
    spec:
      hostNetwork: true
      containers:
        - name: medooze
          image: <your-medooze-image>
```

The trick is to bypass container networking by using `hostNetwork: true`. The standard docker networking uses an iptables rule per port forwarded. This isn't practical with large port ranges. Enabling host networking lets docker bind ports on the host instead.

You can do somthing similar without kubernetes by passing [--network host](https://docs.docker.com/network/host/) when using `docker run`.
